import Head from "next/head";
import { api } from "~/utils/api";
import Form from "~/components/form";

export default function Home() {
  const { data, refetch } = api.leaveForms.findWithinTargetDate.useQuery({});
  const { data: proRatedData, refetch: proRatedRefetch } =
    api.leaveForms.generateProRated.useQuery({});

  console.table(data);

  return (
    <>
      <Head>
        <title>Leaves</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Form refetch={refetch} />
        {JSON.stringify(data)}
        {JSON.stringify(proRatedData)}
      </main>
    </>
  );
}
